apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  myLitKey1: bXlMaXRWYWwx
  myLitKey2: bXlMaXRWYWwy
  myFileKey3: VGhpcyBpcyBmaWxlMyBsaW5lMQpUaGlzIGlzIGZpbGUzIGxpbmUyClRoaXMgaXMgZmlsZTMgbGluZTMK
  myfile4.txt: VGhpcyBpcyBmaWxlNCBsaW5lMQpUaGlzIGlzIGZpbGU0IGxpbmUyClRoaXMgaXMgZmlsZTQgbGluZTMK
  myfile5.txt: VGhpcyBpcyBmaWxlNSBsaW5lMQpUaGlzIGlzIGZpbGU1IGxpbmUyClRoaXMgaXMgZmlsZTUgbGluZTMK
  myfile6.txt: VGhpcyBpcyBmaWxlNiBsaW5lMQpUaGlzIGlzIGZpbGU2IGxpbmUyClRoaXMgaXMgZmlsZTYgbGluZTMK
