apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: volume-from-mysecret
        mountPath: /some/mount/dir
  volumes:
    - name: volume-from-mysecret
      secret:
        secretName: mysecret


  restartPolicy: Never

image: nginx
# all keys in mysecret become variables
envFrom:
- secretRef:
    name: mysecret

image: nginx
# 1 key-of-mysecret becomes 1 var
env:
- name: MY_VAR_NAME
  valueFrom:
    secretKeyRef:
      name: mysecret
      key: key-of-mysecret

