apiVersion: v1
kind: Secret
metadata:
  name: deployhashlocked-chartsecret
  labels:
    {{- include "deployhashlocked.labels" . | nindent 4 }}
type: Opaque

{{- with .Values.deployhashlockedChartsecret }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }} 
