apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: multic8r
spec:
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['/bin/sh', '-c', "echo hi > /hi.txt"]
  containers:
  - image: busybox
    name: busybox2
    args: ["sleep",  '100000']
  - image: busybox
    name: busybox
    args: ["sleep",  '100000']
  - image: nginx
    name: nginx
