apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: dsnginx1
  name: dsnginx1
spec:
  selector:
    matchLabels:
      app: dsnginx1
  template:
    metadata:
      labels:
        app: dsnginx1
    spec:
      containers:
      - image: nginx
        name: nginx
