apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"busybox","namespace":"default"},"spec":{"containers":[{"args":["/bin/sh","-c","sleep 10000"],"image":"busybox","name":"busybox"}]}}
  creationTimestamp: "2021-12-14T23:05:03Z"
  name: busybox
  namespace: default
  resourceVersion: "2603962"
  uid: 22c78269-35f2-4a11-93d0-f9934a1060d3
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 10000
    image: busybox
    imagePullPolicy: Always
    name: busybox
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    envFrom:
    - secretRef:
        name: mysecr
    volumeMounts:
    - name: volm
      mountPath: "/etc/volm"
      readOnly: true
  volumes:
  - name: volm
    secret:
      secretName: mysecr
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3d-myk3dcluster-agent-1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-12-14T23:05:03Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-12-20T10:25:04Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-12-20T10:25:04Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-12-14T23:05:03Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://ef68b2ba5b03876981d13d1e7c811a205c573e08b62501865dc114568cc89189
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:70eb6b39a8db2834d27b221899aa6c30a4d9648c804cf0586d8d6ea202327fe7
    lastState:
      terminated:
        containerID: containerd://92cec29880c3e63951f5d0c4352f985a929916a59c001822709bb9f02d995466
        exitCode: 255
        finishedAt: "2021-12-20T10:24:34Z"
        reason: Unknown
        startedAt: "2021-12-20T09:46:04Z"
    name: busybox
    ready: true
    restartCount: 48
    started: true
    state:
      running:
        startedAt: "2021-12-20T10:25:04Z"
  hostIP: 172.26.0.4
  phase: Running
  podIP: 10.42.2.62
  podIPs:
  - ip: 10.42.2.62
  qosClass: BestEffort
  startTime: "2021-12-14T23:05:03Z"
