apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - command:
        - sleep
        - "100"
        image: busybox
        name: myjob
      restartPolicy: Never
