# Default values for deployhashlocked.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: busybox
  tag: stable

command: ["/bin/sh"]
args: 
- -c
- |
  export VALUE_AT_BOOT=$(cat /secrets/*)
  while true; do 
    echo "Value at boot: $VALUE_AT_BOOT   -----   Value now: $(cat /secrets/*)"
    sleep 1
  done


volumeMounts:
- name: myvolume
  mountPath: /secrets
  readOnly: true

volumes:
- name: myvolume
  secret:
    secretName: deployhashlocked-chartsecret

deployhashlockedChartsecret:
  secretcontent: "SuperSecret2"


podAnnotations: {}






nameOverride: ""
fullnameOverride: ""


