apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: xdep
  name: xdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xdep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: xdep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
