apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: mydaemonset
  name: mydaemonset
spec:
  selector:
    matchLabels:
      app: mydaemonset
  template:
    metadata:
      labels:
        app: mydaemonset
    spec:
      containers:
      - image: nginx
        name: nginx
